//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practica03_G1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alumno
    {
        public string carnet { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public string genero { get; set; }
        public string email { get; set; }
        public string telefono { get; set; }
        public string fecha_nacimiento { get; set; }
    }
}
